### ISSUE TITLE
Support Quarto profiles?

### ISSUE THREAD

**Issue by andrewheiss** [ropensci/tarchetypes#139]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/tarchetypes/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Starting with v1.2, Quarto supports [project profiles](https://quarto.org/docs/projects/profiles.html) that let you customize overall project _quarto.yml files for specific situations, like production vs. development, or basic book vs. advanced book. For instance, these three YAML files define two different versions of a book (via the Quarto documentation)

**_quarto.yml**
```yaml
project:
  type: book
  output-dir: _book
  
book:
  title: "My Book"
  author: "Norah Jones"

profile:
  default: basic
```

**_quarto-basic.yml**
```yaml
book:
  output-file: "basic.pdf"
  chapters:
    - intro.qmd
    - using.qmd
    - summary.qmd
```

**_quarto-advanced.yml**
```yaml
book:
  output-file: "advanced.pdf"
  chapters:
    - intro.qmd
    - using.qmd
    - advanced.qmd
    - summary.qmd
```

It's possible to switch profiles either with environment variables or with a command line switch:

```sh
export QUARTO_PROFILE=basic
quarto render .
```

or 

```
quarto render . --profile advanced
```

Right now, `tar_quarto()` doesn't have a way to switch profiles, so it uses whatever is set to the default (basic in this example). It could be helpful to control environments in order to create targets for multiple profiles. For instance, a pipeline like this could create both _book/basic.pdf and _book/advanced.pdf from one project:

```r
...
tar_quarto(basic_book, path = ".", profile = "basic"),
tar_quarto(advanced_book, path = ".", profile = "advanced")
...
```

…where the profile argument would sets the `QUARTO_PROFILE` environment variable or create a switch option or somehow make Quarto render the file with the specified profile(s)
